### ISSUE TITLE
Zeus command line

### ISSUE THREAD

**Issue by abdounasser202** [Sanix-Darker/zeus#1]
My idea would be to set up a **zeus command line** so we can type
`zeus run path/to/main/file`
It executes the code and when it finds a bug it runs `zeus.go(exception)`
and in an interactive way it helps me to fix my bug

**Comment by Sanix-Darker** [comment]
Of course, that's a really good idea !

**Comment by Sanix-Darker** [comment]
![zeuscli](https://user-images.githubusercontent.com/22576758/66691198-7a1fed00-ec8c-11e9-8818-908d0fceceba.gif)
i Just end this featue and it's working pretty fine, so am closing the issue!
